1st Review for baking app StepDetailFragment.java 1.You need to implement the interface 2.It is required that you release Exoplayer in onPauseor onStop. As per the Google docs
It’s important to release the player when it’s no longer needed, so as to free up limited resources such as video decoders for use by other applications. This can be done by calling ExoPlayer.release.

Have a look at this demo code by Exoplayer team.

3.It is required that you restore the video from the position it has already played and the player's play state.

Currently, the video plays from the start when the screen rotates.
You can save the played video location and mExoPlayer.getPlayWhenReady() in onSaveInstanceState and then restore the video from that location.

You can refer this link https://en.proft.me/2016/10/19/how-saverestore-activitys-and-fragments-state/

 to save the information

StepsAdapter.java

The project is not building as these files are missing.

You can use TextUtils.isEmpty to check for a null or empty string.
5.
Error:(97, 38) error: cannot find symbol variable user_placeholder_error
Error:(96, 44) error: cannot find symbol variable user_placeholder
RecipeDetailActivity.java
6. for detecting in tablet
RecipeAdapter.java
7.It is required that you handle image for recipe in your app even though it is currently null.
You should implement the code to factor this condition before loading the image into an image view.

You can use Picasso or Glide to show the image.

MainActivity.java

8. Instead of Toast you can use Snackbar for better user experience.
You can learn more about Snackbar here